name: GPTSite

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to GitHub Pages'
        required: true

jobs:
  GPTSite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        run: |
          cd $GITHUB_WORKSPACE &&
          git config --global user.email "you@example.com" &&
          git config --global user.name "Your Name" &&
          npm install --package-lock-only &&
          npm ci &&
          npm run build --if-present &&
          git branch -D temp-gh-pages || true &&
          git checkout -b temp-gh-pages &&
          git add . &&
          git commit -m "Deploy to temporary branch" &&
          git push origin temp-gh-pages &&
          git checkout ${{ github.event.before }} &&
          npx gh-pages -d ./build -b gh-pages -m "Deploy to GitHub Pages" -t ${{ secrets.GH_TOKEN }}
